### ISSUE TITLE
digiturk.com.tr changed

### ISSUE THREAD

**Issue by mutluerol** [matthuisman/plugin.video.beinsports.apac#1]
hi Matthuisman,

In Turkei i gues address changed, can you update it ?

thanks

Erol

**Comment by matthuisman** [comment]
No idea what this is about.
This add-on is only for APAC regions (Australia, NZ etc).
Not for Turkey

**Comment by mutluerol** [comment]
Hi,

In your code, there is digiturk


6 | API_BASE = 'https://mobileservice.apac.beiniz.biz{}'
-- | --
7 | WV_LICENSE_URL = 'https://castleblack.digiturk.com.tr/api/widevine/licenseraw?version=1'
8 |  
9 | PAGESIZE = 200

**Comment by matthuisman** [comment]
I've just tested and it it still works.
I've also checked via their website, and the license url is still:
https://castleblack.digiturk.com.tr/api/widevine/licenseraw?version=1
